# https://concourse-ci.org/multi-branch-workflows.html

resource_types:
  - name: git-branches
    type: registry-image
    source:
      repository: aoldershaw/git-branches-resource

resources:
  - name: dev-branches
    type: git-branches
    source:
      uri: https://github.com/dumptruckman/multiverse-core-testing
      branch_regex: '^(?P<dev_branch>((?!main).)*)$'

  - name: main
    type: git
    source:
      uri: https://github.com/dumptruckman/multiverse-core-testing

groups:
  - name: deployments
    jobs:
      #      - unit-tests
      - package
  - name: devops
    jobs:
      - set-dev-branch-pipelines

jobs:
  - name: package
    build_logs_to_retain: 50
    plan:
      - get: main
        trigger: true
      #        passed: [unit-tests]
      - task: maven-package
        file: main/ci/tasks/maven-package.yml

  - name: set-dev-branch-pipelines
    plan:
      - in_parallel:
          - get: dev-branches
            trigger: true
          - get: main
      - load_var: branches
        file: dev-branches/branches.json
      - across:
          - var: branch
            values: ((.:branches))
        set_pipeline: multiverse-core-branch-testing
        file: main/ci/pipelines/multi-branch/template.yml
        instance_vars: { dev_branch: ((.:branch.groups.dev_branch)) }
        vars: { branch: ((.:branch.name)) }